export const words = [
  'Salão de Beleza Copacabana',
  'Cabeleireiro',
  'Manicure',
  'Pedicure',
  'Cabeleireiro Copacabana',
  'Manicure Copacabana',
  'Pedicure Copacabana',
  'Salão de Beleza',
  'Salão de Beleza Zona Sul',
  'Salão de Beleza Ipanema',
  'Cabeleireiro Ipanema',
  'Manicure Ipanema',
  'Pedicure Ipanema',
  'Salão de Beleza Zona Sul',
  'Cabeleireiro Zona Sul',
  'Manicure Zona Sul',
  'Pedicure Zona Sul',
  'Cabelereiros Famosos no Instragam',
  'Cabelereiros Famoso no Rio de Janeiro',
  'Cabelereiros Famoso em Copacabana',
];